before_script:
    - npm install -g grunt-cli
    - npm install -g bower
    - bower install -f --offline

language: node_js
node_js:
    - "0.10"
sudo: false
cache:
  directories:
    - node_modules
    - bower_components
